version: "3"

networks:
    app-network:
      driver: bridge  

volumes:
    pg-escola-data:

services:
    
    db:
        image: postgres:11
        container_name: db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: escola_db
        volumes: 
            - pg-escola-data:/var/lib/postgresql/data
        ports: 
            - "5432:5432" 
        networks: 
            - app-network

    app:
        image: node:lts-alpine
        container_name: app
        restart: always
        working_dir: /app
        command: npm run serve
        volumes: 
            - ./src/app:/app
        ports: 
            - "8080:8080"
        networks: 
            - app-network

    api:
        image: bitnami/php-fpm:7.4
        container_name: api
        restart: always
        working_dir: /app
        command: php artisan serve --host=0.0.0.0 --port=8181 
        volumes: 
            - ./src/api/php.ini:/opt/bitnami/php/etc/conf.d/php.ini
            - ./src/api:/app
        ports: 
            - "8181:8181"
        depends_on: 
            - db
        networks: 
            - app-network